kind: ConfigMap
apiVersion: v1
metadata:
  name: loan-properties
data:
  application.properties : |-
    # Maximum Java heap to be used during the native image generation
    quarkus.native.native-image-xmx=4g
    org.redhat.notation.rest.CompaniesRemoteService/mp-rest/url=http://companies-svc-companies-app.apps.ocp4.ouachani.net
    org.redhat.notation.rest.CompaniesRemoteService/mp-rest/scope=javax.enterprise.context.ApplicationScoped
    quarkus.infinispan-client.sasl-mechanism=PLAIN
    quarkus.infinispan-client.server-list=kogito-infinispan:11222
    quarkus.infinispan-client.use-auth=true
    quarkus.infinispan-client.auth-username=developer
    quarkus.infinispan-client.auth-password=jPBNvQ2uqg@xJ6Pd%
    kogito.service.url=http://localhost:8080
    kogito.dataindex.http.url=data-index:8180
    kogito.dataindex.ws.url=ws://data-index:8180
    
    kafka.bootstrap.servers=kogito-kafka-kafka-bootstrap.companies-app.svc:9092
    mp.messaging.outgoing.noteapplication.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.noteapplication.connector=smallrye-kafka
    mp.messaging.outgoing.noteapplication.topic=noteapplication
    mp.messaging.outgoing.noteapplication.value.serializer=org.apache.kafka.common.serialization.StringSerializer
    mp.messaging.incoming.notnoted.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.incoming.notnoted.connector=smallrye-kafka
    mp.messaging.incoming.notnoted.topic=notnoted
    mp.messaging.incoming.notnoted.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
    mp.messaging.incoming.model1.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.incoming.model1.connector=smallrye-kafka
    mp.messaging.incoming.model1.topic=model1
    mp.messaging.incoming.model1.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

    mp.messaging.outgoing.kogito-jobs-events.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.kogito-jobs-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-jobs-events.topic=kogito-jobs-events
    mp.messaging.outgoing.kogito-jobs-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer


    mp.messaging.outgoing.kogito-processdomain-events.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.kogito-processdomain-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-processdomain-events.topic=kogito-processdomain-events
    mp.messaging.outgoing.kogito-processdomain-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer


    mp.messaging.outgoing.kogito-usertaskdomain-events.bootstrap.servers=${kafka.bootstrap.servers} 
    mp.messaging.outgoing.kogito-usertaskdomain-events.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.kogito-usertaskdomain-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-usertaskdomain-events.topic=kogito-usertaskdomain-events
    mp.messaging.outgoing.kogito-usertaskdomain-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.kogito-processinstances-events.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.kogito-processinstances-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-processinstances-events.topic=kogito-processinstances-events
    mp.messaging.outgoing.kogito-processinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.kogito-usertaskinstances-events.bootstrap.servers=${kafka.bootstrap.servers}   
    mp.messaging.outgoing.kogito-usertaskinstances-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-usertaskinstances-events.topic=kogito-usertaskinstances-events
    mp.messaging.outgoing.kogito-usertaskinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.kogito-variables-events.bootstrap.servers=${kafka.bootstrap.servers}    
    mp.messaging.outgoing.kogito-variables-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-variables-events.topic=kogito-variables-events
    mp.messaging.outgoing.kogito-variables-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer









