apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: bbank-prometheus-datasource
  namespace: bbankapps
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      type: prometheus
      url: 'http://prometheus:9090'
      version: 1
  name: bbank-prometheus-datasource
